spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/clienthub}
    username: ${SPRING_DATASOURCE_USERNAME:clienthub}
    password: ${SPRING_DATASOURCE_PASSWORD:clienthub}

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true