spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/clienthub
    username: clienthub
    password: clienthub

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true