spring:
  datasource:
    # Connect to Docker Database
    url: jdbc:postgresql://localhost:5432/clienthub
    username: clienthub
    password: clienthub

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      # Automatically createt tables from entities
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080